### ISSUE TITLE
You should try out hyperhtml for rendering

### ISSUE THREAD

**Issue by phenax** [yTakkar/Fun-With-Custom-Web-Components#1]
[hyperHTML](https://github.com/WebReflection/hyperHTML)
It can handle the diffing for you for performant updates

Theres also a [hyperHTML wrapper for custom elements spec](https://github.com/WebReflection/hyperHTML-Element)

**Comment by yTakkar** [comment]
Thanks a lot for those cool references, will surely check them out. :)
